runtime: java17
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
inbound_services:
- warmup
service_account: opinio-403522@appspot.gserviceaccount.com